# Generated by Django 2.2.5 on 2019-10-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirt', 'shirt'), ('Sport Wear', 'sport wear'), ('Out Wear', 'Out wear')], default='Shirt', max_length=20),
        ),
    ]
